export const articles = [
  { slug: "types-of-sip-investment", category: "SIP basics", title: "Types of SIP Investment", summary: "Understand regular, top-up and flexible SIP options before choosing what fits your cash flow.", read: "05 min read", body: ["A regular SIP invests a fixed amount at a chosen frequency. It is simple to understand and can make investing a consistent habit.", "A top-up SIP increases the contribution periodically, which may help the investment keep pace as income grows. Flexible approaches allow changes where the platform and scheme permit them.", "The most useful SIP is one that matches a real goal and remains affordable through different market conditions."] },
  { slug: "how-to-open-sip-account-online", category: "Getting started", title: "How to Open a SIP Account Online", summary: "A simple guide to KYC, choosing a fund and starting your first monthly investment.", read: "05 min read", body: ["Begin by completing the required KYC process using your identity, address, PAN and bank information.", "Next, define the goal, time horizon and risk level before comparing suitable mutual fund categories and scheme documents.", "Set an affordable SIP date and amount, authorize the bank mandate and review the plan periodically rather than reacting to daily market moves."] },
  { slug: "understanding-nav-mutual-funds", category: "Mutual fund basics", title: "Understanding NAV in Mutual Funds", summary: "Learn what Net Asset Value means and what it does—and does not—tell you about a fund.", read: "04 min read", body: ["NAV is the per-unit value of a mutual fund scheme after accounting for its assets and liabilities.", "A lower NAV does not automatically mean a fund is cheaper or has greater return potential. Portfolio quality, mandate, risk, cost and consistency matter more.", "Use NAV to understand transaction value and performance over time, not as a stand-alone reason to select a fund."] },
  { slug: "sip-for-retirement-planning", category: "Retirement", title: "SIP for Retirement Planning", summary: "Estimate your retirement need and invest toward it one manageable step at a time.", read: "06 min read", body: ["Retirement planning begins with the lifestyle and monthly expenses you may need after regular income stops.", "Inflation can substantially increase that amount over a long period, so the target corpus and investment contribution should be reviewed regularly.", "A diversified, goal-linked SIP can help build the corpus, while risk should usually reduce as the goal approaches."] },
  { slug: "tax-benefits-of-sip-investment", category: "Tax basics", title: "Tax Benefits of SIP Investment", summary: "Understand where tax benefits may apply and which rules investors should check.", read: "05 min read", body: ["A SIP is only a method of investing; its tax treatment depends on the mutual fund category and applicable tax law.", "SIPs into eligible ELSS schemes may qualify for a deduction under the prevailing rules, and each instalment has its own lock-in period.", "Tax rules change. Review current regulations and consult a qualified tax professional before acting."] },
  { slug: "sip-for-education-planning", category: "Child education", title: "SIP for Education Planning", summary: "Plan for rising education costs with a goal-linked monthly investment.", read: "05 min read", body: ["Start with the current estimated cost of the course and the number of years remaining until the money is needed.", "Apply a reasonable education-inflation assumption, then estimate the monthly investment required to work toward that future amount.", "Review the target each year and gradually protect accumulated money as admission draws closer."] },
  { slug: "sip-vs-term-deposit", category: "Comparison", title: "SIP vs Term Deposit", summary: "Compare market-linked growth potential with the relative predictability of fixed-return savings.", read: "06 min read", body: ["A mutual fund SIP invests periodically in a market-linked scheme, while a term deposit generally offers a stated interest rate for a fixed period.", "SIPs can suit longer goals where market fluctuations are acceptable. Deposits can be useful where capital stability and a known maturity value matter more.", "The right mix depends on the goal, time available, liquidity needs, tax position and ability to accept market risk."] },
  { slug: "factor-analysis-to-beat-the-sp500", category: "Factor research", title: "How to Use Factor Analysis to Beat the S&P 500", summary: "A practical framework for making return drivers visible before they become concentration risk.", read: "08 min read", body: ["Factor analysis does not promise outperformance. It provides a clearer account of the drivers an investor chooses to own.", "Value, quality, momentum, size and low volatility can reveal hidden concentration across otherwise diverse-looking holdings.", "The useful question is not which factor wins next. It is what a portfolio already depends on, and whether that dependence is intentional."] },
  { slug: "rise-of-alternative-data-2025", category: "Data intelligence", title: "The Rise of Alternative Data in 2025", summary: "A measured view of the signals that are reshaping modern investment research.", read: "06 min read", body: ["Alternative data is information generated outside conventional financial statements and formal company guidance.", "Web traffic, supply-chain activity and price data can refine an investment question, but each source requires governance and context.", "One datapoint is a clue. A stable pattern checked against business fundamentals can become evidence."] },
  { slug: "risk-management-strategies-for-volatile-markets", category: "Portfolio design", title: "Risk Management Strategies for Volatile Markets", summary: "Build a decision process that remains useful when uncertainty is highest.", read: "07 min read", body: ["Volatility makes every decision feel urgent. A written risk process restores proportion before an emotional reaction becomes a lasting allocation choice.", "A resilient review considers liquidity, concentration, leverage and investor horizon—not only the price movement on the screen.", "The objective is not to predict the next move. It is to keep the portfolio aligned with the plan."] },
] as const;
