import { LegalPage } from "@/components/legal-page";

export default function DisclosuresPage() {
  return <LegalPage title="Disclosures" intro="Important information about mutual fund risk, costs, distribution and the illustrative material presented by SYDY Capital." sections={[
    ["Mutual fund risk", "Mutual fund investments are exposed to market movements and may also involve credit, liquidity, interest-rate and scheme-specific risks. Returns are not assured or guaranteed. Past performance may not continue, and there is no assurance that a scheme will achieve its stated investment objective. Investors should read the Scheme Information Document, Key Information Memorandum and all other scheme-related documents carefully before investing."],
    ["Costs, exit loads and TER", "Before investing, investors should review the exit load, Total Expense Ratio (TER) and other costs applicable to the selected scheme and plan. These costs can change and may affect investment outcomes. Current information should be verified from the relevant mutual fund or official scheme documents at the time of the transaction."],
    ["Regular Plans and distributor commission", "SYDY Capital facilitates investments in Regular Plans of mutual fund schemes and earns trail commission on eligible client investments. The applicable commission disclosure is provided to the investor at the time of investment. Distribution commission and expenses form part of the cost structure of a Regular Plan."],
    ["Direct Plans", "Every mutual fund scheme may also offer a Direct Plan for investors who choose to invest without a distributor. Direct Plans generally have a lower expense ratio because distributor commission is not included. SYDY Capital does not transact in Direct Plans and does not earn commission on them. Investors should compare both routes and choose the one appropriate for their needs."],
    ["Risk profiling and guided views", "An investor is required to complete risk profiling before investing. Any guided view, category suggestion, calculator result or model allocation on this website is indicative and is based on information voluntarily supplied by the user. It is not a promise of performance, an assurance of suitability for every investor or a substitute for reviewing the relevant scheme documents."],
    ["Independent evaluation", "Each investor should independently assess the merits and risks of an investment, including whether it suits their objectives, financial position, time horizon, liquidity needs and risk capacity. Investors should consult their own financial, legal and tax advisers where appropriate before acting."],
    ["NAV, income distributions and future outcomes", "The NAV of a mutual fund scheme may fluctuate because of market conditions, interest rates and other factors. Any income distribution depends on the availability and adequacy of distributable surplus and is not guaranteed by SYDY Capital. Historical returns, illustrations and examples should not be treated as a guide or promise of future performance."],
    ["Website information", "SYDY Capital aims to keep its website information accurate and useful, but inadvertent omissions, delays or inaccuracies may occur. Information may come from mutual funds and other third parties and should be verified before use. To the extent permitted by applicable law, SYDY Capital is not responsible for losses arising solely from reliance on incomplete or inaccurate website information."],
    ["Illustrative strategies and tools", "Strategy figures, risk statistics, calculators, portfolio views and dashboard data marked as illustrative are interface examples. They are not actual SYDY Capital performance records, offers, research recommendations or guarantees. Verified methodology, benchmarks, costs, taxes and slippage must be considered before evaluating any strategy."],
    ["Third-party marks", "AMC names and trademarks belong to their respective owners. Their appearance is for identification and platform-access context, is subject to verification of current distribution relationships and does not by itself imply endorsement."],
  ]} />;
}
